version: '2'
services:
  zookeeper:
    image: debezium/zookeeper:1.4
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
  kafka:
    image: debezium/kafka:1.4
    ports:
      - 9092:9092
    links:
      - zookeeper
    environment:
      - ZOOKEEPER_CONNECT=zookeeper:2181
  # kafka-ui:

  #   image: provectuslabs/kafka-ui:latest

  #   ports:

  #    - 8080:8080

  #   links:

  #    - kafka

  #   environment:

  #    - KAFKA_CLUSTERS_0_NAME=local

  #    - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
  sqlserver:
    image: microsoft/mssql-server-linux:2017-CU9-GDR2
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_PID=Standard
      - SA_PASSWORD=Password!
      - MSSQL_AGENT_ENABLED=true
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.0
    ports:
      - "9200:9200"
    environment:
      - http.host=0.0.0.0
      - transport.host=127.0.0.1
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  # connect-sql:

  #   image: debezium/connect:1.4

  #   ports:

  #    - 8082:8083

  #   links:

  #    - kafka

  #    - sqlserver

  #   environment:

  #    - BOOTSTRAP_SERVERS=kafka:9092

  #    - GROUP_ID=1

  #    - CONFIG_STORAGE_TOPIC=my_connect_configs

  #    - OFFSET_STORAGE_TOPIC=my_connect_offsets

  #    - STATUS_STORAGE_TOPIC=my_source_connect_statuses
  connect-es:
    image: debezium/connect-jdbc-es:1.4
    build:
      context: debezium-jdbc-es
    ports:
      - 8083:8083
      - 5005:5005
    links:
      - kafka
      - elastic
      - sqlserver
    environment:
      - BOOTSTRAP_SERVERS=kafka:9092
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=my_connect_configs
      - OFFSET_STORAGE_TOPIC=my_connect_offsets
      - STATUS_STORAGE_TOPIC=my_source_connect_statuses
